/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        Train trainSelectedForBooking = null;
        String lastSearchSource = null;
        String lastSearchDestination = null;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch(IOException ex){
            System.out.println("There is something wrong");
            return;
        }

        while (option != 7) {
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            if (!scanner.hasNext()) {
                System.out.println("No input detected. Exiting.");
                break;
            }
            if (!scanner.hasNextInt()) {
                System.out.println("Invalid option. Please enter a number (1-7).");
                scanner.next();
                continue;
            }
            option = scanner.nextInt();
            if (option == 7) {
                System.out.println("Exiting. Bye!");
                break;
            }

            switch (option) {
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();
                    User userToSignup = new User(nameToSignUp, passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    Boolean signedUp = userBookingService.signUp(userToSignup);
                    if (Boolean.TRUE.equals(signedUp)) {
                        System.out.println("Signup successful. You are now logged in.");
                    } else {
                        System.out.println("Signup failed (maybe username already exists).");
                    }
                    break;
                case 2:
                    System.out.println("Enter the username to Login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password to login");
                    String passwordToLogin = scanner.next();
                    User userToLogin = new User(nameToLogin, passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userToLogin);
                        if (Boolean.TRUE.equals(userBookingService.loginUser())) {
                            System.out.println("Login successful.");
                        } else {
                            System.out.println("Invalid username/password.");
                            userBookingService = new UserBookingService();
                        }
                    } catch (IOException ex) {
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBookings();
                    break;
                case 4:
                    System.out.println("Type your source station");
                    String source = scanner.next();
                    System.out.println("Type your destination station");
                    String dest = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source, dest);
                    if (trains.isEmpty()) {
                        System.out.println("No trains found for this route.");
                        break;
                    }
                    lastSearchSource = source;
                    lastSearchDestination = dest;
                    int index = 1;
                    for (Train t : trains) {
                        System.out.println(index + ". Train id : " + t.getTrainId());
                        for (Map.Entry<String, String> entry : t.getStationTimes().entrySet()) {
                            System.out.println("station " + entry.getKey() + " time: " + entry.getValue());
                        }
                        index++;
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    if (!scanner.hasNextInt()) {
                        System.out.println("Invalid selection.");
                        scanner.next();
                        break;
                    }
                    int selectedIndex = scanner.nextInt() - 1;
                    if (selectedIndex < 0 || selectedIndex >= trains.size()) {
                        System.out.println("Invalid selection.");
                        break;
                    }
                    trainSelectedForBooking = trains.get(selectedIndex);
                    break;
                case 5:
                    if (trainSelectedForBooking == null) {
                        System.out.println("Please search and select a train first (option 4).");
                        break;
                    }
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row : seats) {
                        for (Integer val : row) {
                            System.out.print(val + " ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    if (!scanner.hasNextInt()) {
                        System.out.println("Invalid row.");
                        scanner.next();
                        break;
                    }
                    int row = scanner.nextInt();
                    System.out.println("Enter the column");
                    if (!scanner.hasNextInt()) {
                        System.out.println("Invalid column.");
                        scanner.next();
                        break;
                    }
                    int col = scanner.nextInt();
                    System.out.println("Enter date of travel (any text, optional):");
                    String dateOfTravel = scanner.next();
                    System.out.println("Booking your seat....");
                    String sourceForTicket = lastSearchSource == null ? "" : lastSearchSource;
                    String destForTicket = lastSearchDestination == null ? "" : lastSearchDestination;
                    Boolean booked = userBookingService.bookTicket(trainSelectedForBooking, row, col, sourceForTicket, destForTicket, dateOfTravel);
                    if (booked.equals(Boolean.TRUE)) {
                        System.out.println("Booked! Enjoy your journey");
                    } else {
                        System.out.println("Can't book this seat");
                    }
                    break;
                case 6:
                    System.out.println("Enter the ticket id to cancel");
                    String ticketId = scanner.next();
                    userBookingService.cancelBooking(ticketId);
                    break;
                default:
                    System.out.println("Unknown option. Please choose 1-7.");
                    break;
            }
        }

        scanner.close();
    }
}
